module.exports = {
  scenariosData: [
    {
      cardType: 'small',
      icon: 'timer',
      title: 'Я ухожу',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Включить свет в коридоре',
    },
    {
      cardType: 'small',
      icon: 'sun',
      title: 'Сделать пол тёплым во всей квартире',
      isActive: true,
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Выключить весь свет в доме и во дворе',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Набрать горячую ванну',
      subtitle: 'Начнётся в 18:00',
    },
    {
      cardType: 'small',
      icon: 'timer',
      title: 'Я ухожу',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Включить свет в коридоре',
    },
    {
      cardType: 'small',
      icon: 'sun',
      title: 'Сделать пол тёплым во всей квартире',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Выключить весь свет в доме и во дворе',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Набрать горячую ванну',
      subtitle: 'Начнётся в 18:00',
    },
    {
      cardType: 'small',
      icon: 'timer',
      title: 'Я ухожу',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Включить свет в коридоре',
    },
    {
      cardType: 'small',
      icon: 'sun',
      title: 'Сделать пол тёплым во всей квартире',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Выключить весь свет в доме и во дворе',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Набрать горячую ванну',
      subtitle: 'Начнётся в 18:00',
    },
    {
      cardType: 'small',
      icon: 'timer',
      title: 'Я ухожу',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Включить свет в коридоре',
    },
    {
      cardType: 'small',
      icon: 'sun',
      title: 'Сделать пол тёплым во всей квартире',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Выключить весь свет в доме и во дворе',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: 'Набрать горячую ванну',
      subtitle: 'Начнётся в 18:00',
    },
  ],

  devicesData: [
    {
      cardType: 'small',
      filterType: 'lights',
      icon: 'sun2',
      subtitle: 'Включено',
      title: 'Xiaomi Yeelight LED Smart Bulb',
      type: 'slider',
    },
    {
      cardType: 'small',
      filterType: 'cameras',
      icon: 'sun',
      subtitle: 'Включится в 17:00',
      title: 'D-Link Omna 180 Cam',
      type: 'slider',
    },
    {
      cardType: 'small',
      filterType: 'kitchen',
      icon: 'temperature',
      subtitle: 'Выключено до 17:00',
      title: 'Elgato Eve Degree Connected',
      type: 'slider',
    },
    {
      cardType: 'small',
      filterType: 'lights',
      icon: 'sun',
      subtitle: 'Включится в 17:00',
      title: 'LIFX Mini Day & Dusk A60 E27',
      type: 'radial',
    },
    {
      cardType: 'small',
      filterType: 'kitchen',
      icon: 'sun2',
      subtitle: 'Включено',
      title: 'Xiaomi Mi Air Purifier 2S',
      type: 'radial',
    },
    {
      cardType: 'small',
      filterType: 'lights',
      icon: 'sun',
      subtitle: 'Выключено',
      title: 'Philips Zhirui',
      type: 'radial',
    },
    {
      cardType: 'small',
      filterType: 'livingRoom',
      icon: 'sun2',
      subtitle: 'Включено',
      title: 'Xiaomi Mi Air Purifier 2S',
      type: 'radial',
    },
  ],

  plannedData: [
    { icon: 'temperature2', title: 'Philips Cooler', subtitle: 'Начнет охлаждать в 16:30' },
    { icon: 'sun', title: 'Xiaomi Yeelight LED Smart Bulb', subtitle: 'Включится в 17:00' },
    { icon: 'temperature', title: 'Clone - Philips Cooler', subtitle: 'Начнет охлаждать в 16:30' },
    { icon: 'sun', title: 'Clone - Xiaomi Yeelight LED Smart Bulb', subtitle: 'Включится в 17:00' },
  ],
};
