module.exports = {
  scenariosData: [
    {
      cardType: 'small',
      icon: 'timer',
      title: ' 1 / 20 - Я ухожу',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 2 / 20 - Включить свет в коридоре',
    },
    {
      cardType: 'small',
      icon: 'sun',
      title: ' 3 / 20 - Сделать пол тёплым во всей квартире',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 4 / 20 - Выключить весь свет в доме и во дворе',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 5 / 20 - Набрать горячую ванну',
      subtitle: 'Начнётся в 18:00',
    },
    {
      cardType: 'small',
      icon: 'timer',
      title: ' 6 / 20 - Я ухожу',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 7 / 20 - Включить свет в коридоре',
    },
    {
      cardType: 'small',
      icon: 'sun',
      title: ' 8 / 20 - Сделать пол тёплым во всей квартире',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 9 / 20 - Выключить весь свет в доме и во дворе',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 10 / 20 - Набрать горячую ванну',
      subtitle: 'Начнётся в 18:00',
    },
    {
      cardType: 'small',
      icon: 'timer',
      title: ' 11 / 20 - Я ухожу',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 12 / 20 - Включить свет в коридоре',
    },
    {
      cardType: 'small',
      icon: 'sun',
      title: ' 13 / 20 - Сделать пол тёплым во всей квартире',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 14 / 20 - Выключить весь свет в доме и во дворе',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 15 / 20 - Набрать горячую ванну',
      subtitle: 'Начнётся в 18:00',
    },
    {
      cardType: 'small',
      icon: 'timer',
      title: ' 16 / 20 - Я ухожу',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 17 / 20 - Включить свет в коридоре',
    },
    {
      cardType: 'small',
      icon: 'sun',
      title: ' 18 / 20 - Сделать пол тёплым во всей квартире',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 19 / 20 - Выключить весь свет в доме и во дворе',
    },
    {
      cardType: 'small',
      icon: 'sun2',
      title: ' 20 / 20 - Набрать горячую ванну',
      subtitle: 'Начнётся в 18:00',
    },
  ],

  devicesData: [
    {
      value: 0.3,
      min: 0,
      max: 1,
      cardType: 'small',
      filterType: 'lights',
      icon: 'sun2',
      title: '1 / 7 - Xiaomi Yeelight LED Smart Bulb',
      subtitle: 'Включено',
    },
    {
      value: 0.3,
      min: 0,
      max: 1,
      cardType: 'small',
      filterType: 'cameras',
      icon: 'sun',
      title: '2 / 7 - D-Link Omna 180 Cam',
      subtitle: 'Включится в 17:00',
    },
    {
      min: -10,
      max: 30,
      value: 20,
      cardType: 'small',
      filterType: 'kitchen',
      icon: 'temperature',
      title: '3 / 7 - Elgato Eve Degree Connected',
      subtitle: 'Выключено до 17:00',
    },
    {
      value: 0.3,
      min: 0,
      max: 1,
      cardType: 'small',
      filterType: 'lights',
      icon: 'sun',
      title: '4 / 7 - LIFX Mini Day & Dusk A60 E27',
      subtitle: 'Включится в 17:00',
    },
    {
      value: 0.3,
      min: 0,
      max: 1,
      cardType: 'small',
      filterType: 'kitchen',
      icon: 'sun2',
      title: '5 / 7 - Xiaomi Mi Air Purifier 2S',
      subtitle: 'Включено',
    },
    {
      value: 0.3,
      min: 0,
      max: 1,
      cardType: 'small',
      filterType: 'lights',
      icon: 'sun',
      title: '6 / 7 - Philips Zhirui',
      subtitle: 'Выключено',
    },
    {
      value: 0.3,
      min: 0,
      max: 1,
      cardType: 'small',
      filterType: 'livingRoom',
      icon: 'sun2',
      title: '7 / 7 - Xiaomi Mi Air Purifier 2S',
      subtitle: 'Включено',
    },
  ],

  plannedData: [
    { icon: 'temperature2', title: '1 - Philips Cooler', subtitle: 'Начнет охлаждать в 16:30' },
    { icon: 'sun', title: '2 - Xiaomi Yeelight LED Smart Bulb', subtitle: 'Включится в 17:00' },
    { icon: 'temperature', title: '3 - Clone - Philips Cooler', subtitle: 'Начнет охлаждать в 16:30' },
    { icon: 'sun', title: '4 - Clone - Xiaomi Yeelight LED Smart Bulb', subtitle: 'Включится в 17:00' },
  ],
};
